# Generated by Django 4.0.3 on 2022-03-29 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prob', models.FloatField(default=0.0)),
                ('task', models.IntegerField(choices=[(1, 'Sequence Classification'), (2, 'Relation Extraction')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('annotated', models.BooleanField(default=False)),
                ('metadata', models.TextField(default='{}')),
                ('belongs_to', models.IntegerField(choices=[(0, 'Train'), (1, 'Dev'), (2, 'Test')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='hilt_annotation.document')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysisAnnotation',
            fields=[
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sentiment_analysis_annotation', serialize=False, to='hilt_annotation.annotation')),
            ],
        ),
        migrations.CreateModel(
            name='WordAnnotationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_annotation_score', to='hilt_annotation.annotation')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_annotation_score', to='hilt_annotation.word')),
            ],
        ),
        migrations.CreateModel(
            name='RelationExtractionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbj_start_offset', models.PositiveIntegerField()),
                ('sbj_end_offset', models.PositiveIntegerField()),
                ('obj_start_offset', models.PositiveIntegerField()),
                ('obj_end_offset', models.PositiveIntegerField()),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relation_extraction_annotation', to='hilt_annotation.annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('task', models.IntegerField(choices=[(1, 'sequence classification'), (2, 'Relation Extraction')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('color_set', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='hilt_annotation.project')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hilt_annotation.project'),
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=256)),
                ('explanation_type', models.IntegerField(choices=[(1, 'Local Explanation'), (2, 'Global Explanation')], default=1)),
                ('annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_dictionary', to='hilt_annotation.annotation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_dictionary', to='hilt_annotation.project')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='hilt_annotation.document'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='hilt_annotation.label'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['document'], name='word_document_index'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'text')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project'], name='document_project_index'),
        ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['project'], name='dictionary_project_index'),
        ),
        migrations.AlterUniqueTogether(
            name='dictionary',
            unique_together={('project', 'word')},
        ),
    ]
