# Generated by Django 4.0.3 on 2022-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0002_annotation_document_word_sentimentanalysisannotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='belongs_to',
            field=models.IntegerField(choices=[(0, 'Train'), (1, 'Dev'), (2, 'Test')], default=0),
        ),
    ]
