# Generated by Django 4.0.3 on 2022-04-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0003_globalexplanationdictionary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
    ]
