# Generated by Django 4.0.3 on 2022-03-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0003_document_belongs_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'text')},
        ),
    ]
