# Generated by Django 4.0.3 on 2022-08-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0005_word_word_text_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ground_truth',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth_document', to='hilt_annotation.label'),
        ),
    ]
