# Generated by Django 4.0.3 on 2022-08-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0006_document_ground_truth'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalexplanationdictionary',
            name='modification_type',
            field=models.IntegerField(choices=[(0, 'Add'), (1, 'Remove')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localexplanationdictionary',
            name='modification_type',
            field=models.IntegerField(choices=[(0, 'Add'), (1, 'Remove')], default=0),
            preserve_default=False,
        ),
    ]
