# Generated by Django 4.0.3 on 2022-08-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0007_globalexplanationdictionary_modification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalexplanationdictionary',
            name='ground_truth_label',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth_global_exp', to='hilt_annotation.label'),
            preserve_default=False,
        ),
    ]
