# Generated by Django 4.0.3 on 2022-10-26 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0008_globalexplanationdictionary_ground_truth_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.IntegerField(choices=[(1, 'Sequence Classification'), (2, 'Relation Extraction')], default=1),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('model', models.FileField(upload_to='models/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='hilt_annotation.project')),
            ],
        ),
    ]
