# Generated by Django 4.0.3 on 2022-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0009_alter_project_task_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='HiltModel',
        ),
        migrations.AddField(
            model_name='project',
            name='selected_model',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
