# Generated by Django 4.0.3 on 2023-01-25 01:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hilt_annotation', '0011_rename_selected_model_project_debugging_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiltmodel',
            name='debug',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WordDebugAnnotationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_debug_annotation_score', to='hilt_annotation.annotation')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_debug_annotation_score', to='hilt_annotation.hiltmodel')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_debug_annotation_score', to='hilt_annotation.word')),
            ],
        ),
    ]
