_target_: src.utils.logging.get_neptune_logger

logger: neptune

log_db: manual_runs
tag_attrs: 
  - ${data.dataset}
  - ${model.model}
  - ${model.arch}
name: test
offline: True
project_name: danny911kr/test